// ════════════════════════════════════════════
//  GYAKORLAT-KÖNYVTÁR
// ════════════════════════════════════════════
// Izomcsoportokra bontott gyakorlatlista a tervezőhöz. A felhasználó ebből
// választhat, vagy manuálisan is megadhat sajátot. A lista bővíthető.
// Vegyesen tartalmaz bevett (súlyzós, gépes, saját testsúlyos) és
// felszerelés-specifikus (Smith, kábel/KS, landmine) gyakorlatokat.

export const EXERCISE_LIBRARY = [
  { group:'Mell', items:[
    'Fekvenyomás (rúd)',
    'Ferde fekvenyomás (rúd)',
    'Smith Gépes Fekvenyomás',
    'Ferde Smith Fekvenyomás',
    'Tárogatás',
    'Ferde Tárogatás',
    '15 fok KS Mell',
    'KS Áthúzás',
    'Tárcsás Tolódzkodás',
    'Gépes Mellnyomás',
    'Fekvőtámasz',
  ]},
  { group:'Hát', items:[
    'Húzódzkodás',
    'Fordított Fogású Húzódzkodás',
    'Széles Lehúzás',
    'Szűk Fogású Lehúzás',
    'Széles Evezés',
    'Felső Evezés',
    'Rúd Evezés (rod)',
    'Egykezes Tárcsás Evezés',
    'T-rúd Evezés',
    'Kábeles Evezés',
    'Hyperextenzió',
    'Deadlift',
    'Pulóver',
  ]},
  { group:'Váll', items:[
    'Vállból Nyomás (rúd)',
    'Ülő Tárcsás Vállnyomás',
    'Smith Gépes Vállnyomás',
    'Landmine Nyomás',
    'Oldalemelés',
    'Kábeles Oldalemelés',
    'Előreemelés',
    'Facepull Ülve',
    'Fordított Tárogatás (hátsó deltoid)',
    'Arnold Nyomás',
    'Rúd Húzás Állig',
  ]},
  { group:'Bicepsz', items:[
    'Scott Pados Karhajlítás',
    'Kereszttestes Kalapács',
    'KS Bicepsz',
    'Kalapács',
    'Rúd Bicepsz',
    'EZ-rúd Bicepsz',
    'Koncentrált Karhajlítás',
    'Kábeles Bicepsz',
    'Spider Karhajlítás',
  ]},
  { group:'Tricepsz', items:[
    'Fejfeletti Tricepsz',
    'Koponyatörő',
    'Tricepsz Letolás',
    'JM Nyomás Smith Gépen',
    'Tricepsz fej fölött kötéllel',
    'Szűk Fogású Fekvenyomás',
    'Tolódzkodás (tricepsz)',
    'Kötél Letolás',
    'Egykezes Kábel Letolás',
  ]},
  { group:'Láb', items:[
    'Guggolás',
    'Első Guggolás (front squat)',
    'Smith Gépes Guggolás',
    'Lábtoló',
    'Láb Extenzió',
    'Hátsócomb Hajlítás',
    'Comb Hajtás',
    'RDL (román felhúzás)',
    'Smith Gépes Kitörés',
    'Kitörés (sétáló)',
    'Bolgár Kitörés',
    'Vádli (állva)',
    'Vádli (ülve)',
    'Csípő Addukció',
  ]},
  { group:'Far / Csípő', items:[
    'Csípőtolás (hip thrust)',
    'Glute Bridge',
    'Kábeles Hátrarúgás',
    'Gépes Glute',
    'Csípő Abdukció (gépes)',
    'Tárcsás Csípőtolás',
  ]},
  { group:'Hasizom', items:[
    'Hashoz Húzás (kábel crunch)',
    'Lábemelés (fekve)',
    'Lábemelés (függeszkedve)',
    'Has Csípő Csavarás',
    'Plank',
    'Oldalsó Plank',
    'Orosz Csavarás',
    'Crunch',
    'Bicikli Crunch',
  ]},
  { group:'Törzs / Core', items:[
    'Oldalra Dőlés (oldalhajlítás)',
    'Pallof Nyomás',
    'Dead Bug',
    'Bird Dog',
    'Farmer Séta',
  ]},
];
